version: "3.3"
services:
  test:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - "$PWD:$PWD"
    working_dir: "$PWD"
    ports:
      - "8000"
    depends_on:
        - db
    environment:
      - DB_URL=postgres://postgres:dbpass@db:5432/db
      - DB_URL_TEST=postgres://postgres:dbpass@db:5432/db
      - RATEJSON_FXCM_URL=https://fake.url
    networks:
      - custom
    command: pytest

  db:
    image: postgres:11.0-alpine
    environment:
        - POSTGRES_PASSWORD=dbpass
        - POSTGRES_DB=db
    ports:
        - "5432:5432"
    networks:
        - custom
    logging:
      driver: none

networks:
  custom:
    driver: bridge
