"""
add financial assets table
"""

from yoyo import step

__depends__ = {}

steps = [
    step(
        """
        CREATE TABLE IF NOT EXISTS financial_assets (
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            symbol text NOT NULL,
            created_at timestamp with time zone not null,
            updated_at timestamp with time zone not null,
            is_deleted bool not null
        )
        """,
        """
        DROP TABLE IF EXISTS financial_assets;
        """,
    ),
    step(  # Пока нет интерфейса добавим пары через датамиграцию
        """
        INSERT INTO financial_assets (symbol, created_at, updated_at, is_deleted) VALUES 
        ('EURUSD', now(), now(), FALSE),
        ('USDJPY', now(), now(), FALSE),
        ('GBPUSD', now(), now(), FALSE),
        ('AUDUSD', now(), now(), FALSE),
        ('USDCAD', now(), now(), FALSE)
        """,
        """
        TRUNCATE TABLE financial_assets;
        """,
    ),
]
